// web-platform/vue-app/src/components/Common/Modal.vue
<template>
  <Transition
    enter-active-class="transition duration-200 ease-out"
    enter-from-class="transform scale-95 opacity-0"
    enter-to-class="transform scale-100 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="transform scale-100 opacity-100"
    leave-to-class="transform scale-95 opacity-0"
  >
    <div
      v-if="modelValue"
      class="fixed inset-0 z-50 overflow-y-auto"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="title ? `${id}-title` : undefined"
      :aria-describedby="description ? `${id}-description` : undefined"
    >
      <!-- Backdrop -->
      <div
        class="fixed inset-0 bg-black/50 transition-opacity dark:bg-black/75"
        @click="closeOnBackdrop && close()"
      />

      <!-- Modal Container -->
      <div class="flex min-h-full items-center justify-center p-4 text-center">
        <!-- Modal Panel -->
        <div
          class="relative w-full max-w-lg transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all dark:bg-gray-800"
          :class="[
            {
              'sm:max-w-sm': size === 'sm',
              'sm:max-w-lg': size === 'md',
              'sm:max-w-2xl': size === 'lg',
              'sm:max-w-4xl': size === 'xl'
            }
          ]"
        >
          <!-- Header -->
          <div
            v-if="$slots.header || title"
            class="border-b border-gray-200 px-4 py-5 dark:border-gray-700 sm:px-6"
          >
            <slot name="header">
              <div class="flex items-center justify-between">
                <h3
                  :id="`${id}-title`"
                  class="text-lg font-medium leading-6 text-gray-900 dark:text-white"
                >
                  {{ title }}
                </h3>

                <!-- Close Button -->
                <button
                  v-if="showClose"
                  type="button"
                  class="rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:hover:text-gray-300 dark:focus:ring-offset-gray-800"
                  @click="close()"
                >
                  <span class="sr-only">Close</span>
                  <XMarkIcon class="h-6 w-6" />
                </button>
              </div>
            </slot>
          </div>

          <!-- Body -->
          <div
            v-if="$slots.default"
            class="px-4 py-5 sm:p-6"
          >
            <slot />
          </div>

          <!-- Footer -->
          <div
            v-if="$slots.footer"
            class="border-t border-gray-200 px-4 py-4 dark:border-gray-700 sm:px-6"
          >
            <slot name="footer" />
          </div>
        </div>
      </div>
    </div>
  </Transition>
</template>

<script setup>
import { XMarkIcon } from '@heroicons/vue/20/solid'

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true
  },
  id: {
    type: String,
    required: true
  },
  title: {
    type: String,
    default: ''
  },
  description: {
    type: String,
    default: ''
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg', 'xl'].includes(value)
  },
  showClose: {
    type: Boolean,
    default: true
  },
  closeOnBackdrop: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['update:modelValue'])

const close = () => {
  emit('update:modelValue', false)
}
</script>

// components/Modal.tsx
import React, { useEffect, useRef } from 'react';
import { XIcon, FileTextIcon } from './icons/Icons';

interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    title: string;
    children: React.ReactNode;
}

const Modal: React.FC<ModalProps> = ({ isOpen, onClose, title, children }) => {
    const modalRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handleKeyDown = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                onClose();
            }
        };

        const focusableElementsString = 'a[href], button:not([disabled]), textarea, input, select';
        
        const handleFocusTrap = (event: KeyboardEvent) => {
            if (event.key === 'Tab' && modalRef.current) {
                const focusableElements = modalRef.current.querySelectorAll<HTMLElement>(focusableElementsString);
                const firstElement = focusableElements[0];
                const lastElement = focusableElements[focusableElements.length - 1];

                if (event.shiftKey) {
                    if (document.activeElement === firstElement) {
                        lastElement.focus();
                        event.preventDefault();
                    }
                } else {
                    if (document.activeElement === lastElement) {
                        firstElement.focus();
                        event.preventDefault();
                    }
                }
            }
        };

        if (isOpen) {
            document.addEventListener('keydown', handleKeyDown);
            document.addEventListener('keydown', handleFocusTrap);
            modalRef.current?.querySelector<HTMLElement>(focusableElementsString)?.focus();
        }

        return () => {
            document.removeEventListener('keydown', handleKeyDown);
            document.removeEventListener('keydown', handleFocusTrap);
        };
    }, [isOpen, onClose]);


    if (!isOpen) return null;

    return (
        <div 
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
            onClick={onClose}
            role="dialog"
            aria-modal="true"
            aria-labelledby="modal-title"
        >
            <div
                ref={modalRef}
                className="relative bg-white dark:bg-neutral-800 rounded-lg shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col m-4 animate-fade-in-up"
                onClick={(e) => e.stopPropagation()} // Prevent closing when clicking inside
            >
                <div className="flex items-center justify-between p-4 border-b border-neutral-200 dark:border-neutral-700">
                    <h2 id="modal-title" className="text-lg font-bold text-neutral-800 dark:text-neutral-100 flex items-center">
                        <FileTextIcon className="h-5 w-5 mr-3 text-trust-blue dark:text-ai-teal" />
                        {title}
                    </h2>
                    <button 
                        onClick={onClose} 
                        className="p-1 rounded-full text-neutral-500 hover:bg-neutral-200 dark:hover:bg-neutral-700 hover:text-neutral-800 dark:hover:text-neutral-100 transition-colors"
                        aria-label="Close modal"
                    >
                        <XIcon className="h-6 w-6" />
                    </button>
                </div>
                <div className="p-6 overflow-y-auto prose prose-neutral dark:prose-invert max-w-none">
                   {children}
                </div>
                 <div className="p-4 border-t border-neutral-200 dark:border-neutral-700 text-right">
                    <button 
                        onClick={onClose}
                        className="px-4 py-2 bg-trust-blue hover:bg-trust-blue-light dark:bg-ai-teal dark:hover:bg-ai-teal-light text-white font-semibold rounded-md shadow-sm transition-colors"
                    >
                        Close
                    </button>
                </div>
            </div>
             <style>{`
                @keyframes fade-in-up {
                    from {
                        opacity: 0;
                        transform: translate3d(0, 1rem, 0) scale(0.95);
                    }
                    to {
                        opacity: 1;
                        transform: translate3d(0, 0, 0) scale(1);
                    }
                }
                .animate-fade-in-up {
                    animation: fade-in-up 0.3s ease-out forwards;
                }
            `}</style>
        </div>
    );
};

export default Modal;
